FROM fedora:28

RUN dnf install -y autoconf
RUN dnf install -y automake
RUN dnf install -y libmpc-devel
RUN dnf install -y mpfr-devel
RUN dnf install -y gmp-devel
RUN dnf install -y gawk
RUN dnf install -y bison
RUN dnf install -y flex
RUN dnf install -y texinfo
RUN dnf install -y patchutils
RUN dnf install -y gcc
RUN dnf install -y gcc-c++
RUN dnf install -y zlib-devel
RUN dnf install -y expat-devel
RUN dnf install -y make
